### ISSUE TITLE
关于store在不同模块间得使用问题

### ISSUE THREAD

**Issue by linjiayue** [BothEyes1993/vue-multi-module#10]
- `project2`中某一个组件使用了`project2`中`stroe`得内容，这时`project1`引用`project2`中得该组件，`project2`中得使用到得`store`并没有被自动引用到`project1`中，我现在只能在`project1`得`store`中引入`project2`得`store`，该组件才能正常使用，请问有什么好得解决办法吗？

**Comment by BothEyes1993** [comment]
原则上各个项目的store是独立的不应该互相依赖，如果一定有依赖建议新建立一个独立comm模块提供各个项目的公共数据依赖
