### ISSUE TITLE
你好，cli3是不是就是通过pages来实现

### ISSUE THREAD

**Issue by xubillde** [BothEyes1993/vue-multi-module#12]
https://blog.csdn.net/xlz26296/article/details/79133441

https://blog.csdn.net/weixin_43588821/article/details/109132115?utm_medium=distribute.pc_relevant.none-task-blog-baidujs_title-1&spm=1001.2101.3001.4242

第二个cli3的思路对吗？

**Comment by xubillde** [comment]
https://cli.vuejs.org/zh/config/#indexpath

没看到入口配置entry

**Comment by BothEyes1993** [comment]
是的，cli3以后可以用pages实现多界面入口，入口配置在pages对象里面

**Comment by xubillde** [comment]
好的，多谢哈
