### ISSUE TITLE
多模块打包

### ISSUE THREAD

**Issue by Handsome00000** [BothEyes1993/vue-multi-module#7]
你好，请教个问题，现在如果是全部打包所有模块的话，会在dist文件下生成各个模块的文件。包括重复的vendor，并且没有统一的index。html 入口， 我怎么提交给后端放到服务器上呢？

**Comment by BothEyes1993** [comment]
打包是各个项目独立的，不会合在一起，你要合在一起就在开发项目的时候做好模块依赖，然后打包这个项目
